### ISSUE TITLE
when the song played, it gave me a link to another song. 

### ISSUE THREAD

**Issue by BagonGanda** [wibbuffey/SongBirb-Archive#1] opened 2021-06-10 02:08 UTC
it is as the title says, when i was listening to xenoblade music, and as it went to another one, a pokemon link was there but a xenoblade theme was playing.

**Comment by wibbuffey** [comment] 2021-06-10 02:09
duplicate of #2 with less info (26 seconds apart)

**Closed as completed by wibbuffey** 2021-06-10 02:09 UTC
Labels: bug, duplicate

**Comment by wibbuffey** [comment] 2021-06-10 02:11
update: #2 seems to have been later, however #2 has more info.
